version: '3'
services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgress
            - POSTGRES_DB=postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5555:5432
volumes:
    db-data: